server:
  error:
    include-stacktrace: never
  servlet:
    context-path: /api
  port: 8083
spring:
  boot:
    message: Hello! Organization Service ! (PURE)
  datasource:
    password: rootpassword
    url: jdbc:mysql://localhost:3306/organization-db
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: ORGANIZATION-SERVICE
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
